// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_ART.Data;

#nullable disable

namespace Project_ART.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220915064622_AddToDb")]
    partial class AddToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project_ART.Models.TableAssessment", b =>
                {
                    b.Property<int>("Assessment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assessment_ID"), 1L, 1);

                    b.Property<int?>("Assessed_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Assessed")
                        .HasColumnType("datetime2");

                    b.Property<int>("Exam_ID")
                        .HasColumnType("int");

                    b.Property<int>("Interview_ID")
                        .HasColumnType("int");

                    b.HasKey("Assessment_ID");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Project_ART.Models.TableCandidate", b =>
                {
                    b.Property<int>("Candidate_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Candidate_ID"), 1L, 1);

                    b.Property<int>("Application_ID")
                        .HasColumnType("int");

                    b.Property<int>("Assessment_ID")
                        .HasColumnType("int");

                    b.Property<int>("Hired_By")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Hired")
                        .HasColumnType("bit");

                    b.HasKey("Candidate_ID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Project_ART.Models.TableDatasheet", b =>
                {
                    b.Property<int>("Data_Sheet_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Data_Sheet_ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Initial")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Mobile_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Data_Sheet_ID");

                    b.ToTable("Datasheets");
                });

            modelBuilder.Entity("Project_ART.Models.TableEmployee", b =>
                {
                    b.Property<int>("Company_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_ID"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middle_Initial")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Mobile_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Project_ART.Models.TableExam", b =>
                {
                    b.Property<int>("Exam_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Exam_ID"), 1L, 1);

                    b.Property<double>("Exam_Score")
                        .HasColumnType("float");

                    b.HasKey("Exam_ID");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Project_ART.Models.TableInterview", b =>
                {
                    b.Property<int>("Interview_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Interview_ID"), 1L, 1);

                    b.Property<double>("Interview_Score")
                        .HasColumnType("float");

                    b.HasKey("Interview_ID");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("Project_ART.Models.TableIntroduction", b =>
                {
                    b.Property<int>("Introduction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Introduction_ID"), 1L, 1);

                    b.Property<string>("B5_Trait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISC_Trait")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Introduction_ID");

                    b.ToTable("Introductions");
                });

            modelBuilder.Entity("Project_ART.Models.TableJobApplication", b =>
                {
                    b.Property<int>("Application_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Application_ID"), 1L, 1);

                    b.Property<int>("Approved_By")
                        .HasColumnType("int");

                    b.Property<string>("DataSheet_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Received")
                        .HasColumnType("datetime2");

                    b.Property<string>("Introduction_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Is_Approved")
                        .HasColumnType("bit");

                    b.HasKey("Application_ID");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("Project_ART.Models.TableKeyword", b =>
                {
                    b.Property<int>("Key_Word_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key_Word_ID"), 1L, 1);

                    b.Property<int>("Introduction_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time_Stamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key_Word_ID");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("Project_ART.Models.TableRecruiter", b =>
                {
                    b.Property<int>("Recruiter_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recruiter_ID"), 1L, 1);

                    b.Property<int>("Company_ID")
                        .HasColumnType("int");

                    b.Property<bool?>("Is_Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Recruiter_ID");

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("Project_ART.Models.TableSkill", b =>
                {
                    b.Property<int>("Skill_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Skill_ID"), 1L, 1);

                    b.Property<int>("Data_Sheet_ID")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Skill_ID");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
